AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an S3 bucket with configurable name and versioning.

Parameters:
  BucketName:
    Description: Name of the S3 bucket
    Type: String
  VersioningEnabled:
    Description: Enable or disable versioning
    Type: String
    AllowedValues: [Enabled, Disabled]
    Default: Disabled

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !If
          - IsVersioningEnabled
          - Enabled
          - !Ref "AWS::NoValue"

Conditions:
  IsVersioningEnabled: !Equals [!Ref VersioningEnabled, Enabled]
